# Generated by Django 5.1.3 on 2025-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="country_code",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
