# Generated by Django 5.1.3 on 2025-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_storetoproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_digital",
            field=models.CharField(
                blank=True,
                choices=[("True", "True"), ("False", "False")],
                default="False",
                max_length=5,
                null=True,
            ),
        ),
    ]
