# Generated by Django 5.1.3 on 2025-03-10 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_wishlist_country_delivery_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
