# Generated by Django 5.1.3 on 2025-03-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_delivery_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="is_complete",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="is_delivered",
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Reversed", "Reversed"),
                ],
                null=True,
            ),
        ),
    ]
