# Generated by Django 5.1.3 on 2025-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_delivery_is_complete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="status",
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Reversed", "Reversed"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
